// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdiXS8RL4ARIXAMAB5BamxTp3dmW0rInA',
    appId: '1:157929659832:web:2f873866aaafa3bb1d434d',
    messagingSenderId: '157929659832',
    projectId: 'cashblack-project',
    authDomain: 'cashblack-project.firebaseapp.com',
    storageBucket: 'cashblack-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3gx7FAj6Q1LWN5fuq8JXGrQQrSpe7ylM',
    appId: '1:157929659832:android:2b8221b5367109a11d434d',
    messagingSenderId: '157929659832',
    projectId: 'cashblack-project',
    storageBucket: 'cashblack-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClkOfAxCqXTo5jq4kOr2TAo6NLKRbwUg4',
    appId: '1:157929659832:ios:20ea148518685bf11d434d',
    messagingSenderId: '157929659832',
    projectId: 'cashblack-project',
    storageBucket: 'cashblack-project.firebasestorage.app',
    iosBundleId: 'com.cashblackdevteam.cashblack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClkOfAxCqXTo5jq4kOr2TAo6NLKRbwUg4',
    appId: '1:157929659832:ios:20ea148518685bf11d434d',
    messagingSenderId: '157929659832',
    projectId: 'cashblack-project',
    storageBucket: 'cashblack-project.firebasestorage.app',
    iosBundleId: 'com.cashblackdevteam.cashblack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdiXS8RL4ARIXAMAB5BamxTp3dmW0rInA',
    appId: '1:157929659832:web:4675ded415d064401d434d',
    messagingSenderId: '157929659832',
    projectId: 'cashblack-project',
    authDomain: 'cashblack-project.firebaseapp.com',
    storageBucket: 'cashblack-project.firebasestorage.app',
  );
}
